pipeline {
  agent {
    docker {
      image 'executeautomation/jenkinsagent:agent'
    }

  }
  stages {
    stage('SCM') {
        steps {
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/executeautomation/JenkinsPipelines']]])
	    }
    }
    stage('Build') {
          steps {
               sh 'dotnet build "$WORKSPACE/src/EAApp.csproj"'
          }
        }

    stage('Publish') {
          steps {
              archiveArtifacts artifacts: 'src/*.*'
          }
        }
  }
  environment {
    SELENIUM = 'c:\\driver\\win'
    VARIABLE = ''
  }
}
